[package]
name = "awatcher"
version = "0.0.1"
authors = ["Demmie <2e3s19@gmail.com>"]
edition = "2021"

[[bin]]
name = "awatcher"
path = "src/main.rs"

[workspace]
members = ["watchers"]

[workspace.dependencies]
anyhow = "1.0.70"
log = { version = "0.4.17", features = ["std"] }

[dependencies]
watchers = { path = "./watchers", default-features = false }
chrono = "0.4.24"
toml = "0.7.3"
clap = { version = "4.2.1", features = ["string"] }
fern = { version = "0.6.2", features = ["colored"] }
log = { workspace = true }
anyhow = { workspace = true }
signal-hook = "0.3.15"

ksni = {version = "0.2.0", optional = true}
aw-server = { git = "https://github.com/ActivityWatch/aw-server-rust.git", optional = true, rev = "49b2026" }
aw-datastore = { git = "https://github.com/ActivityWatch/aw-server-rust.git", optional = true, rev = "49b2026" }
smol = {version = "1.3.0", optional = true }
async-compat = { version = "0.2.1", optional = true }
webbrowser = { version = "0.8.9", optional = true }
zip-extract = { version = "0.1.2", default-features = false, features = ["deflate"], optional = true  }

[features]
default = ["gnome", "kwin_window"]
gnome = ["watchers/gnome"]
kwin_window = ["watchers/kwin_window"]
bundle = ["ksni", "smol", "async-compat", "aw-server", "aw-datastore", "webbrowser", "zip-extract"]
