[package]
name = "watchers"
version = "0.0.1"
authors = ["Demmie <2e3s19@gmail.com>"]
edition = "2021"

[lib]
name = "watchers"
crate-type = ["lib"]
path = "src/lib.rs"

[dependencies]
aw-client-rust = { git = "https://github.com/ActivityWatch/aw-server-rust" }
wayland-client = "0.30.1"
wayland-scanner = "0.30"
wayland-backend = "0.1"
x11rb = { version = "0.11.1", features = ["screensaver"] }
zbus = {version = "3.11.1", optional = true}
chrono = "0.4.24"
toml = "0.7.3"
dirs = "5.0.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_default = "0.1.0"
serde_json = "1.0.95"
regex = "1.8.1"
log = { workspace = true }
anyhow = { workspace = true }

[features]
default = ["gnome", "kwin_window"]
gnome = ["zbus"]
kwin_window = ["zbus"]
