[package]
name = "watchers"
version = { workspace = true }
authors = ["Demmie <2e3s19@gmail.com>"]
edition = "2021"

[lib]
name = "watchers"
crate-type = ["lib"]
path = "src/lib.rs"

[dev-dependencies]
rstest = "0.17.0"

[dependencies]
aw-client-rust = { git = "https://github.com/2e3s/aw-server-rust", rev = "81db4c8" }
wayland-client = "0.30.2"
wayland-scanner = "0.30"
wayland-backend = "0.1"
x11rb = { version = "0.12.0", features = ["screensaver"] }
zbus = {version = "3.13.1", optional = true}
chrono = "0.4.26"
toml = "0.7.4"
dirs = "5.0.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_default = "0.1.0"
serde_json = "1.0.96"
regex = "1.8.3"
gethostname = "0.4.3"
log = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1.68"
tokio = { workspace = true, features = ["time", "sync"] }

[features]
default = ["gnome", "kwin_window"]
gnome = ["zbus"]
kwin_window = ["zbus"]
