name: Check

on:
  push:
    branches:
    - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --check --all
  clippy-bundle:
    runs-on: ubuntu-latest
    env:
      AW_WEBUI_DIR: ${{ github.workspace }}/src/bundle
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libdbus-1-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-11-01
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --locked --all-targets --all-features --workspace -- -D warnings
  clippy:
    runs-on: ubuntu-latest
    env:
      AW_WEBUI_DIR: ${{ github.workspace }}/src/bundle
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libdbus-1-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --locked --all-targets --workspace -- -D warnings
  test:
    runs-on: ubuntu-latest
    env:
      AW_WEBUI_DIR: ${{ github.workspace }}/src/bundle
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libdbus-1-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-11-01
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features --workspace
