on:
  push:
    branches:
    - main
  pull_request:

name: check

env:
  CARGO_TERM_COLOR: always
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --check --all
  clippy:
    runs-on: ubuntu-latest
    env:
      AW_WEBUI_DIST: ./src/bundle
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y libdbus-1-dev
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --locked --all-targets --all-features --workspace -- -D warnings
